name: Get-ARM64-Docker-Images-Release

on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写docker镜像名称，多个用英文逗号分开'
        required: true
        default: 'alpine:latest,alpine/curl,busybox:stable-glibc'

permissions:
  contents: write   # 必须，用于创建 Release 和上传附件

jobs:
  pull_and_package:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull Docker Images and Package
        run: |
          images="${{ github.event.inputs.docker_images }}"
          IFS=',' read -r -a image_array <<< "$images"
          
          for image in "${image_array[@]}"; do
            image=$(echo "$image" | xargs)  # 清理空格
            echo "🚀 Pulling: $image (linux/arm64)"
            docker pull "${image}" --platform "linux/arm64"
            
            # 生成安全的文件名
            image_name="${image//\//_}"
            image_name="${image_name//:/_}"
            tar_name="${image_name}-arm64.tar"
            gz_name="${image_name}-arm64.tar.gz"
            
            echo "💾 Saving: $gz_name"
            docker save "${image}" -o "$tar_name"
            gzip -c "$tar_name" > "$gz_name"
            rm -f "$tar_name"
          done

      - name: List generated files
        run: |
          echo "✅ Generated files:"
          find $GITHUB_WORKSPACE -name "*.tar.gz" -ls
          release_name=$(TZ="Asia/Shanghai" date +'%Y-%m-%d %H:%M Build')
          echo "RELEASE_NAME=$release_name" >> $GITHUB_ENV

      - name: Create GitHub Release and Upload Assets
        uses: softprops/action-gh-release@v3
        with:
          tag_name: DockerTarBuilder-ARM64
          name: ${{ env.RELEASE_NAME }} for ARM64
          body: |
            [![Github](https://img.shields.io/badge/RELEASE:DockerTarBuilder-123456?logo=github&logoColor=fff&labelColor=green&style=for-the-badge)](https://www.bilibili.com/video/BV1EZ421M7mL)
            [![国内加速站下载](https://img.shields.io/badge/国内加速站下载-FC7C0D?logo=github&logoColor=fff&labelColor=000&style=for-the-badge)](https://wkdaily.cpolar.top/archives/1)

            ### 使用方法示例
            ```bash
            docker load -i alpine_latest-arm64.tar.gz
